name: Setup Java Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup-java:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Java using setup-java action (V2 or V3)
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        # Specify the Java version you want to set up
        java-version: '17'
        distribution: 'temurin' # Options: 'zulu', 'adopt', 'adoptium', 'temurin', etc.
        cache: 'gradle' # Options: gradle, maven, or none

    # Verify Java installation
    - name: Verify Java version
      run: java -version
