name: Setup Java Workflow for V2/V3

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup-java-v2:
    name: Setup Java with V2
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java using setup-java action (V2)
      - name: Setup Java (V2)
        uses: actions/setup-java@v2
        with:
          java-version: '17' # Specify the Java version
          distribution: 'temurin' # Options: 'zulu', 'adopt', 'adoptium', etc.
          cache: 'maven' # Options: gradle, maven, or none

      # Verify Java installation
      - name: Verify Java version (V2)
        run: java -version

  setup-java-v3:
    name: Setup Java with V3
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java using setup-java action (V3)
      - name: Setup Java (V3)
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Specify the Java version
          distribution: 'temurin' # Options: 'zulu', 'adopt', 'adoptium', etc.
          cache: 'gradle' # Options: gradle, maven, or none

      # Verify Java installation
      - name: Verify Java version (V3)
        run: java -version
